// JavaScript/28/react/src/App.jsx
import { useState } from 'react'
import sun from '/sun.png'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div>
          <img src={sun} className="sun" alt="sun" />
      </div>
      <h1>Hello world!</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
      </div>
    </>
  )
}

export default App

// JavaScript/28/vue/src/App.vue
<script setup>
import HelloWorld from "./components/HelloWorld.vue";
</script>

<template>
  <div>
    <img
      src="/sun.png"
      class="sun"
      alt="sun"
    />
  </div>
  <HelloWorld msg="Hello world!" />
</template>

<style scoped>
.sun {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.sun:hover {
  filter: drop-shadow(0 0 2em rgba(250, 255, 100, 0.99));
}
</style>
